packages:
  - '.'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  sharp: false
minimumReleaseAgeExclude:
  - react-hook-form@7.78.0
  - nodemailer@9.0.0
  - lucide-react@1.20.0 || 1.22.0 || 1.34.0
  - react-resizable-panels@4.12.0 || 4.12.3
  - '@typescript-eslint/eslint-plugin@8.68.0'
  - '@typescript-eslint/parser@8.68.0'
  - '@typescript-eslint/project-service@8.68.0'
  - '@typescript-eslint/scope-manager@8.68.0'
  - '@typescript-eslint/tsconfig-utils@8.68.0'
  - '@typescript-eslint/type-utils@8.68.0'
  - '@typescript-eslint/types@8.68.0'
  - '@typescript-eslint/typescript-estree@8.68.0'
  - '@typescript-eslint/utils@8.68.0'
  - '@typescript-eslint/visitor-keys@8.68.0'
  - eslint@10.9.1
  - resend@6.22.1
