import type { Metadata } from 'next'
import HomePageClient from './components/HomePageClient'

export const metadata: Metadata = {
  title: 'adinfinity | Διαφημιστική Εταιρεία Άρτα - Marketing Agency & Digital Services',
  description: 'Η adinfinity είναι κορυφαία διαφημιστική εταιρεία στην Άρτα με 100+ πελάτες. Marketing, digital advertising, εκτυπώσεις, γραφιστική, ιστοσελίδες, διανομή εντύπων. Επαγγελματικές υπηρεσίες με αποτελέσματα! +30 2681 303007',
  keywords: [
    'adinfinity',
    'ad infinity',
    'adinity',
    'adinfit',
    'infiniry',
    'infinity',
    'infinity ad',
    'infinity company',
    'infinity the coffee project',
    'διαφημιστική εταιρεία',
    'διαφημιστικη',
    'διαφημιστική εταιρεία Άρτα',
    'διαφημιστικη εταιρεια',
    'διαφημιστικη εταιρια',
    'marketing agency',
    'agency',
    'marketing company',
    'media agency',
    'εταιρεία',
    'εταιρια',
    'εταιρειεσ',
    'διαφήμιση',
    'διαφήμιση Άρτα',
    'διαφημιστικα',
    'διαφημιστικεσ',
    'διαφημιστικο',
    'διαφημιστικα δωρα',
    'διαφημιστικα δωρα επιχειρησεων',
    'διαφημιστικα προιοντα',
    'διαφημιστικα ειδη',
    'διαφημιστικα στυλο',
    'διαφημιστικα φυλλαδια',
    'διαφημιστικεσ κουπες',
    'διαφημιστική πινακίδα',
    'διαφήμιση επιχείρησησ',
    'διαφήμιση google',
    'διαφημιστικές υπηρεσίες',
    'marketing',
    'marketing Άρτα',
    'digital marketing',
    'digital advertising',
    'advertising',
    'advertising agency',
    'social media agency',
    'grafik',
    'grafis',
    'grafis art',
    'graphic art',
    'graphic design',
    'graphic designs',
    'grafik design',
    'grafisiki',
    'grafisiki',
    'grafisiki',
    'γραφιστικη',
    'γραφιστική',
    'γραφιστικο γραφειο',
    'γραφιστικα γραφεια',
    'γραφικά γραφεία',
    'γραφικές τέχνες',
    'γραφιστική',
    'επιγραφεσ',
    'επιγραφεσ γραμματα',
    'εκτυπώσεις',
    'εκτυπώσεις Άρτα',
    'εκτυπωση φυλλαδιων',
    'εκτυπωσεις',
    'εκτυπωσεισ',
    'εκτυπωσεισ κοντα μου',
    'διανομη εντυπων',
    'διανομή εντύπων',
    'διανομές εντύπων',
    'έντυποδιανομές',
    'εταιρειεσ διανομησ φυλλαδιων',
    'ιστοσελίδες',
    'ιστοσελίδες Άρτα',
    'έντυποδιανομές Άρτα',
    'έρευνα αγοράς',
    'έρευνα ανταγωνισμού',
    'διαφημιστικές υπηρεσίες',
    'digital marketing',
    'digital advertising',
    'advertising agency',
    'social media agency',
    'arta agency',
    'marketing company',
    'media agency',
    'business services',
    'creative agency',
    'brand development',
    't-shirt printing',
    't-shirt printing near me',
    'affinity',
    'forex',
  ],
  alternates: {
    canonical: 'https://adinfinity.gr/',
    languages: {
      'el-GR': 'https://adinfinity.gr',
      'el': 'https://adinfinity.gr',
    },
  },
  openGraph: {
    title: 'adinfinity | Διαφημιστική Εταιρεία Άρτα - Marketing & Digital Services',
    description: 'Η adinfinity είναι κορυφαία διαφημιστική εταιρεία στην Άρτα. Marketing, digital advertising, εκτυπώσεις, γραφιστική. Μετατρέπουμε ιδέες σε επιτυχίες!',
    url: 'https://adinfinity.gr',
    siteName: 'adinfinity',
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: 'adinfinity - Μετατρέπουμε Ιδέες σε Επιτυχίες!',
      },
    ],
    locale: 'el_GR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'adinfinity | Διαφημιστική Εταιρεία Άρτα',
    description: 'Κορυφαία διαφημιστική εταιρεία στην Άρτα. Marketing, digital services, εκτυπώσεις, γραφιστική.',
    images: ['/images/og-image.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function Home() {
  return <HomePageClient />
}
