// =============================================================================
// SEO meta keywords — SINGLE SOURCE OF TRUTH
// =============================================================================
// All <meta name="keywords"> values for every page live here, for both locales.
// Curate keywords in THIS file only — do not scatter them back into page/layout
// metadata blocks.
//
// Usage:
//   import { getKeywords } from '@/lib/keywords'
//   // inside generateMetadata({ params }) where a locale is known:
//   keywords: getKeywords('prints', locale)
//   // inside a static `export const metadata` (no locale):
//   keywords: getKeywords('prints')            // defaults to 'el'
//
// `page` keys mirror the route path (e.g. 'website-development/e-commerce').
// English (`en`) only needs an entry where it genuinely differs from Greek;
// otherwise getKeywords() falls back to the Greek list.
// =============================================================================

export type Locale = 'el' | 'en'

/** Brand + common brand-misspelling variations reused across many pages. */
const brand = [
  'adinfinity',
  'ad infinity',
  'adinity',
  'adinfit',
  'infiniry',
  'infinity ad',
  'adi infinity',
]

// -----------------------------------------------------------------------------
// Greek (default locale)
// -----------------------------------------------------------------------------
const el: Record<string, string[]> = {
  // Global / site-wide (was messages/el/seo.json → keywords)
  site: [
    'adinfinity',
    'ad infinity',
    'adinity',
    'adinfit',
    'infiniry',
    'infinity',
    'infinity ad',
    'infinity company',
    'infinity the coffee project',
    'διαφημιστική',
    'διαφημιστικη',
    'διαφημιστική εταιρεία',
    'διαφημιστική εταιρεία Άρτα',
    'διαφημιστικη εταιρεια',
    'διαφημιστικη εταιρια',
    'διαφημιστικεσ εταιρειεσ',
    'εταιρεία',
    'εταιρια',
    'εταιρειεσ',
    'διαφήμιση',
    'διαφήμιση Άρτα',
    'διαφημιστικα',
    'διαφημιστικεσ',
    'διαφημιστικο',
    'διαφημιστικα δωρα',
    'διαφημιστικα δωρα επιχειρησεων',
    'διαφημιστικα προιοντα',
    'διαφημιστικα ειδη',
    'διαφημιστικα στυλο',
    'διαφημιστικα φυλλαδια',
    'διαφημιστικεσ κουπες',
    'διαφημιστική πινακίδα',
    'διαφήμιση επιχείρησησ',
    'διαφήμιση google',
    'διαφημιστικές υπηρεσίες',
    'marketing',
    'marketing Άρτα',
    'digital marketing',
    'digital advertising',
    'advertising',
    'advertising agency',
    'social media agency',
    'marketing agency',
    'agency',
    'marketing company',
    'media agency',
    'grafik',
    'grafis',
    'grafis art',
    'graphic art',
    'graphic design',
    'graphic designs',
    'grafik design',
    'γραφιστικη',
    'γραφιστική',
    'γραφιστικο γραφειο',
    'γραφιστικα γραφεια',
    'γραφικά γραφεία',
    'γραφικές τέχνες',
    'επιγραφεσ',
    'επιγραφεσ γραμματα',
    'εκτυπώσεις',
    'εκτυπώσεις Άρτα',
    'εκτυπωση φυλλαδιων',
    'εκτυπωσεις',
    'εκτυπωσεισ',
    'εκτυπωσεισ κοντα μου',
    'διανομη εντυπων',
    'διανομή εντύπων',
    'διανομές εντύπων',
    'έντυποδιανομές',
    'εταιρειεσ διανομησ φυλλαδιων',
    'ιστοσελίδες',
    'ιστοσελίδες Άρτα',
    'έρευνα αγοράς',
    'έρευνα ανταγωνισμού',
    'branding',
    't-shirt printing',
    't-shirt printing near me',
    'flyer distribution',
    'print services',
    'arta agency',
    'Άρτα',
    'Ελλάδα',
    'Greece',
    'creative agency',
    'web development',
    'web design',
    'affinity',
    'forex',
    'διαφημιστική Κύπρος',
    'διαφημιστική εταιρεία Κύπρος',
    'marketing Κύπρος',
    'graphic design Κύπρος',
    'Μάνος Κόσμας',
    'Μάνος Κόσμας adinfinity',
    'Μάνος Κόσμας διαφημιστική',
    'Manos Kosmas',
    'Manos Kosmas adinfinity',
  ],

  // Home (app/page.tsx)
  home: [
    'adinfinity',
    'ad infinity',
    'adinity',
    'adinfit',
    'infiniry',
    'infinity',
    'infinity ad',
    'infinity company',
    'infinity the coffee project',
    'διαφημιστική',
    'διαφημιστικη',
    'διαφημιστική εταιρεία',
    'διαφημιστική εταιρεία Άρτα',
    'διαφημιστικη εταιρεια',
    'διαφημιστικη εταιρια',
    'διαφημιστικεσ εταιρειεσ',
    'marketing agency',
    'agency',
    'marketing company',
    'media agency',
    'εταιρεία',
    'εταιρια',
    'εταιρειεσ',
    'διαφήμιση',
    'διαφήμιση Άρτα',
    'διαφημιστικα',
    'διαφημιστικεσ',
    'διαφημιστικο',
    'διαφημιστικα δωρα',
    'διαφημιστικα δωρα επιχειρησεων',
    'διαφημιστικα προιοντα',
    'διαφημιστικα ειδη',
    'διαφημιστικα στυλο',
    'διαφημιστικα φυλλαδια',
    'διαφημιστικεσ κουπες',
    'διαφημιστική πινακίδα',
    'διαφήμιση επιχείρησησ',
    'διαφήμιση google',
    'διαφημιστικές υπηρεσίες',
    'marketing',
    'marketing Άρτα',
    'digital marketing',
    'digital advertising',
    'advertising',
    'advertising agency',
    'social media agency',
    'grafik',
    'grafis',
    'grafis art',
    'graphic art',
    'graphic design',
    'graphic designs',
    'grafik design',
    'grafisiki',
    'grafisiki',
    'grafisiki',
    'γραφιστικη',
    'γραφιστική',
    'γραφιστικο γραφειο',
    'γραφιστικα γραφεια',
    'γραφικά γραφεία',
    'γραφικές τέχνες',
    'γραφιστική',
    'επιγραφεσ',
    'επιγραφεσ γραμματα',
    'εκτυπώσεις',
    'εκτυπώσεις Άρτα',
    'εκτυπωση φυλλαδιων',
    'εκτυπωσεισ',
    'εκτυπωσεισ κοντα μου',
    'διανομη εντυπων',
    'διανομή εντύπων',
    'διανομές εντύπων',
    'έντυποδιανομές',
    'εταιρειεσ διανομησ φυλλαδιων',
    'ιστοσελίδες',
    'ιστοσελίδες Άρτα',
    'έντυποδιανομές Άρτα',
    'έρευνα αγοράς',
    'έρευνα ανταγωνισμού',
    'διαφημιστικές υπηρεσίες',
    'digital marketing',
    'digital advertising',
    'advertising agency',
    'social media agency',
    'arta agency',
    'marketing company',
    'media agency',
    'business services',
    'creative agency',
    'brand development',
    't-shirt printing',
    't-shirt printing near me',
    'affinity',
    'forex',
  ],

  // Services (merged from app/services/layout.tsx + app/services/page.tsx)
  services: [
    'υπηρεσίες διαφήμισης',
    'διαφημιστικές υπηρεσίες',
    'διαφημιστικη εταιρεια',
    'marketing services',
    'marketing agency',
    'agency Άρτα',
    'εκτυπώσεις Άρτα',
    'γραφιστικη',
    'γραφικές τέχνες',
    'διανομη εντυπων',
    'διανομή εντύπων',
    'έντυποδιανομές',
    'ανάπτυξη ιστοσελίδων',
    'ιστοσελίδες',
    'έρευνα αγοράς',
    'digital marketing',
    'advertising services',
    'marketing υπηρεσίες',
    'digital marketing Άρτα',
    'γραφιστική Άρτα',
    'ιστοσελίδες Άρτα',
    'creative agency',
    'business solutions',
    'επαγγελματικές υπηρεσίες',
    'εταιρικές λύσεις',
    'προβολή επιχείρησης',
    'digital strategy',
  ],

  // Prints (app/prints/layout.tsx)
  prints: [
    'εκτυπώσεις Άρτα',
    'εκτυπωσεισ κοντα μου',
    'εκτυπώσεις κοντά μου',
    'digital printing',
    'διαφημιστικές εκτυπώσεις',
    'premium εκτυπώσεις',
    'banner εκτυπώσεις',
    'flyers εκτυπώσεις',
    'επαγγελματικές εκτυπώσεις',
    'διαφημιστικά δώρα',
    'εκτυπώσεις φυλλάδια',
    'εκτυπώσεις εντυπα',
    'business cards printing',
    'poster printing',
    'large format printing',
  ],

  // Graphic design (app/graphic-design/layout.tsx)
  'graphic-design': [
    ...brand,
    'γραφικές τέχνες',
    'γραφιστική',
    'graphic design',
    'graphic design services',
    'professional graphic design',
    'graphic design agency',
    'graphic design company',
    'γραφιστική άρτα',
    'graphic design artas',
    'design services',
    'branding',
    'εταιρική ταυτότητα',
    'corporate identity',
    'logo design',
    'σχεδιασμός λογοτύπων',
    'διαφημιστικό υλικό',
    'advertising design',
    'social media graphics',
    'digital design',
    'επαγγελματικές κάρτες',
    'business cards',
    'flyers',
    'αφίσες',
    'posters',
    'brochures',
    'κατάλογοι',
    'catalogs',
    'παquetaging',
    'συσκευασία',
    'web design',
    'ui design',
    'ux design',
    'social media design',
    'digital marketing',
    'content creation',
    'γραφιστική άρτα',
    'graphic design artas',
    'γραφιστική ιωαννίνων',
    'graphic design ioannina',
    'γραφιστική ηπείρου',
    'graphic design epirus',
    'γραφιστική βόρειου ελλάδας',
    'επαγγελματική γραφιστική',
    'ποιοτικό design',
    'creative design',
    'custom design',
    'original design',
    'καινοτόμος σχεδιασμός',
    'εκτυπώσεις',
    'printing',
    'διαφημιστική εταιρεία',
    'advertising agency',
    'marketing',
    'branding agency',
  ],

  // Flyer distribution (app/flyer-distribution/layout.tsx)
  'flyer-distribution': [
    ...brand,
    'διανομή φυλλαδίων',
    'διανομη εντυπων',
    'flyer distribution',
    'leaflet distribution',
    'έντυποδιανομές',
    'εντυποδιανομές άρτα',
    'flyer distribution artas',
    'πόρτα πόρτα διανομή',
    'door to door distribution',
    'στοχευμένη διανομή',
    'targeted distribution',
    'διανομή σε οικίες',
    'residential distribution',
    'διανομή σε επιχειρήσεις',
    'business distribution',
    'B2B distribution',
    'διαφημιστική διανομή',
    'advertising distribution',
    'διαφημιστικά φυλλάδια',
    'marketing flyers',
    'προβολή επιχείρησης',
    'business promotion',
    'direct marketing',
    'print advertising',
    'διανομή άρτα',
    'διανομή artas',
    'διανομή ιωαννίνων',
    'distribution ioannina',
    'διανομή ηπείρου',
    'distribution epirus',
    'διανομή βόρειου ελλάδας',
    'distribution northern greece',
    'επαγγελματική διανομή',
    'professional distribution',
    'αποτελεσματική διανομή',
    'effective distribution',
    'γρήγορη διανομή',
    'fast distribution',
    'αξιόπιστη διανομή',
    'reliable distribution',
    'εκτυπώσεις',
    'printing',
    'διαφημιστική εταιρεία',
    'advertising agency',
    'marketing',
    'digital marketing',
    'promotional materials',
  ],

  // Market research (app/market-research/layout.tsx)
  'market-research': [
    'έρευνα αγοράς Άρτα',
    'ανάλυση αγοράς',
    'έρευνα καταναλωτών',
    'έρευνα ανταγωνισμού',
    'market research Greece',
    'marketing research',
    'ανάλυση δεδομένων',
    'business intelligence',
    'competitor analysis',
    'consumer insights',
    'market analysis',
    'στρατηγική μάρκετινγκ',
  ],

  // Invitations (app/invitations/layout.tsx)
  invitations: [
    'ψηφιακές γαμήλιες προσκλήσεις',
    'ψηφιακές προσκλήσεις γάμου',
    'online γαμήλιες προσκλήσεις',
    'ηλεκτρονικές προσκλήσεις γάμου',
    'digital wedding invitations Greece',
    'digital wedding invitations',
    'RSVP online γάμος',
    'online RSVP',
    'διαχείριση καλεσμένων γάμου',
    'γαμήλιο website',
    'mini wedding website',
    'video πρόσκληση γάμου',
    'video wedding invitation',
    'ψηφιακή πρόσκληση γάμου',
    'προσκλήσεις γάμου Ελλάδα',
    'wedding invitation Greece',
    'γαμήλιες προσκλήσεις Άρτα',
    'adinfinity προσκλήσεις',
    'invitations adinfinity',
    'online γαμήλιες προσκλήσεις Ελλάδα',
    'ψηφιακές προσκλήσεις RSVP',
  ],

  // Projects (app/projects/layout.tsx)
  projects: [
    ...brand,
    'έργα adinfinity',
    'portfolio adinfinity',
    'case studies',
    'projects portfolio',
    'work portfolio',
    'client projects',
    'design portfolio',
    'branding',
    'logo design',
    'brand identity',
    'visual identity',
    'brand development',
    'corporate identity',
    'brand strategy',
    'logo creation',
    'graphic design',
    'digital design',
    'print design',
    'marketing design',
    'visual communication',
    'creative design',
    'design services',
    'web design',
    'website design',
    'ui design',
    'ux design',
    'responsive design',
    'web development',
    'marketing campaigns',
    'digital marketing',
    'advertising',
    'promotion materials',
    'marketing collateral',
    'διαφημιστικά έργα',
    'portfolio Άρτα',
    'branding Άρτα',
    'graphic design Ελλάδα',
    'design projects greece',
    'creative agency greece',
    'creative agency',
    'design studio',
    'advertising agency',
    'visual design',
    'branding agency',
    'design solutions',
    'creative solutions',
  ],

  // About (app/about/layout.tsx)
  about: [
    ...brand,
    'about adinfinity',
    'ποιοι είμαστε',
    'who we are',
    'our team',
    'η ομάδα μας',
    'our story',
    'η ιστορία μας',
    'company history',
    'ιστορία εταιρείας',
    'manos kosmas',
    'μάνος κωσμάς',
    'konstantinos blavakis',
    'κωνσταντίνος μπλαβάκης',
    'creative team',
    'δημιουργική ομάδα',
    'marketing team',
    'ομάδα μάρκετινγκ',
    'adinfinity άρτα',
    'adinfinity arta',
    'διαφημιστική εταιρεία',
    'creative agency',
    'advertising agency',
    'digital agency',
    'marketing agency',
    'digital marketing',
    'graphic design',
    'web development',
    'printing services',
    'flyer distribution',
    'market research',
    'άρτα',
    'arta',
    'ηπειρος',
    'epirus',
    'greece',
    'ελλάδα',
    'professional services',
    'business solutions',
    'creative solutions',
    'marketing solutions',
    'digital solutions',
  ],

  // Contact (app/contact/layout.tsx)
  contact: [
    'επικοινωνία adinfinity',
    'contact adinfinity',
    'adinfinity τηλέφωνο',
    'adinfinity email',
    'επικοινωνία διαφημιστική',
    'contact advertising agency',
    'web development contact',
    'graphic design contact',
    'digital marketing contact',
    'Άρτα επικοινωνία',
    'Arta contact',
    'adinfinity',
    'ad infinity',
    'adinity',
    'adinfit',
    'infiniry',
    'infinity ad',
    'custom web development',
    'graphic design services',
    'digital marketing agency',
    'printing services',
    'flyer distribution',
    'web development Greece',
    'digital marketing Arta',
    'Arta advertising agency',
    'Άρτα διαφημιστική',
    'Greece web development',
    'Ελλάδα digital marketing',
  ],

  // Pricing (app/pricing) — new; page previously had no metadata
  pricing: [
    'τιμές adinfinity',
    'τιμοκατάλογος adinfinity',
    'τιμές ιστοσελίδων Άρτα',
    'κόστος ιστοσελίδας',
    'τιμές γραφιστικής',
    'τιμές εκτυπώσεων Άρτα',
    'τιμές διανομής φυλλαδίων',
    'κόστος digital marketing',
    'τιμές έρευνας αγοράς',
    'τιμές διαφημιστικών υπηρεσιών',
    'διαφανείς τιμές',
    'προσφορές adinfinity',
    'pricing advertising agency Arta',
  ],

  // Website development hub (app/website-development/layout.tsx)
  'website-development': [
    ...brand,
    'κατασκευή ιστοσελίδων',
    'κατασκευη web εφαρμογων',
    'κατασκευη web εφαρμογών',
    'web development',
    'custom web apps',
    'react development',
    'nextjs development',
    'typescript development',
    'custom websites',
    'business websites',
    'professional web development',
    'κατασκευή eshop',
    'ecommerce development',
    'online store development',
    'custom ecommerce',
    'stripe integration',
    'payment systems',
    'technical SEO',
    'SEO optimization',
    'web performance',
    'core web vitals',
    'schema markup',
    'speed optimization',
    'mobile optimization',
    'landing pages',
    'web applications',
    'SaaS development',
    'dashboard development',
    'booking systems',
    'portal development',
    'react developer',
    'next.js developer',
    'typescript developer',
    'tailwind css',
    'node.js development',
    'postgresql database',
    'vercel deployment',
    'greek web developer',
    'ελληνική κατασκευή ιστοσελίδων',
    'development ελλάδα',
    'web development greece',
    'custom development athens',
    'professional websites greece',
    'digital marketing',
    'graphic design',
    'ui/ux design',
    'figma design',
    'responsive design',
    'mobile-first development',
    'online presence',
    'business website',
    'company website',
    'professional website',
    'custom solutions',
    'web solutions',
  ],

  // E-commerce (app/website-development/e-commerce/layout.tsx)
  'website-development/e-commerce': [
    ...brand,
    'κατασκευή eshop',
    'ecommerce development',
    'online store development',
    'custom ecommerce',
    'e-shop κατασκευή Ελλάδα',
    'custom online stores',
    'next.js ecommerce',
    'react ecommerce',
    'stripe integration',
    'typescript development',
    'custom web development',
    'shopify alternative',
    'woocommerce alternative',
    'no platform fees',
    'custom ecommerce solution',
    'zero monthly fees',
    'payment gateway integration',
    'stripe payments greece',
    'online payment systems',
    'apple pay integration',
    'google pay integration',
    'greek ecommerce developer',
    'ελληνική κατασκευή eshop',
    'ecommerce greece',
    'online stores athens',
    'professional ecommerce greece',
    'custom admin panel',
    'inventory management',
    'order management system',
    'analytics dashboard',
    'automated workflows',
    'online business',
    'digital store',
    'e-commerce solution',
    'professional online store',
    'custom development',
  ],

  // Landing pages (app/website-development/landing-pages/layout.tsx)
  'website-development/landing-pages': [
    ...brand,
    'landing page development',
    'landing page Greece',
    'κατασκευή landing page',
    'landing page Ελλάδα',
    'custom landing pages',
    'high converting landing pages',
    'landing page optimization',
    'Google Ads landing pages',
    'campaign landing pages',
    'conversion optimization',
    'CRO optimization',
    'digital marketing pages',
    'lead generation pages',
    'Next.js landing pages',
    'React landing pages',
    'TypeScript landing pages',
    'static landing pages',
    'mobile-first landing pages',
    'product launch pages',
    'event registration pages',
    'webinar landing pages',
    'lead magnet pages',
    'squeeze pages',
    'greek landing pages',
    'ελληνικές landing pages',
    'landing pages Αθήνα',
    'landing pages Θεσσαλονίκη',
    'digital marketing Greece',
    'conversion rate',
    'lead generation',
    'sales funnel',
    'marketing campaigns',
    'online advertising',
    'PPC landing pages',
  ],

  // Web apps (app/website-development/web-apps/layout.tsx)
  'website-development/web-apps': [
    ...brand,
    'web applications',
    'SaaS platforms',
    'custom dashboards',
    'react development',
    'nodejs development',
    'full-stack development',
    'custom web apps',
    'web app development',
    'business applications',
    'web εφαρμογές',
    'SaaS πλατφόρμες',
    'custom dashboards',
    'react development',
    'nodejs',
    'full-stack development',
    'ελληνικός web developer',
    'συστήματα κρατήσεων',
    'admin tools',
    'web εφαρμογές',
    'ανάπτυξη εφαρμογών',
    'custom software',
    'business applications',
    'React 19',
    'Next.js 16.2',
    'TypeScript',
    'Node.js',
    'PostgreSQL',
    'Express.js',
    'REST APIs',
    'WebSockets',
    'booking systems',
    'admin dashboards',
    'data platforms',
    'API integrations',
    'custom tools',
    'internal tools',
    'automation workflows',
    'business solutions',
    'digital transformation',
    'enterprise applications',
    'cloud applications',
    'scalable web apps',
  ],

  // Custom web apps (app/website-development/custom-web-apps/layout.tsx)
  'website-development/custom-web-apps': [
    ...brand,
    'custom web apps',
    'εταιρικές ιστοσελίδες',
    'custom website development',
    'web application development',
    'εταιρική ιστοσελίδα',
    'custom ιστοσελίδα',
    'web εφαρμογές',
    'custom web applications',
    'next.js development',
    'react development',
    'typescript development',
    'tailwind css',
    'custom development',
    'web design',
    'ui ux design',
    'hospitality website',
    'education platform',
    'healthcare website',
    'e-commerce website',
    'booking system',
    'admin dashboard',
    'subscription system',
    'professional web development',
    'custom web solutions',
    'mobile-first design',
    'seo optimization',
    'fast loading',
    'secure websites',
    'web development greece',
    'custom websites artas',
    'web development ioannina',
    'web development epirus',
    'custom web apps northern greece',
    'digital marketing',
    'graphic design',
    'printing',
    'flyer distribution',
    'business promotion',
    'online presence',
  ],

  // Technical SEO (app/website-development/technical-seo/layout.tsx)
  'website-development/technical-seo': [
    'technical SEO Greece',
    'Core Web Vitals',
    'SEO βελτιστοποίηση',
    'speed optimization',
    'schema markup',
    'Lighthouse audit',
  ],

  // Maintenance (merged app/website-development/maintenance/layout.tsx + page.tsx)
  'website-development/maintenance': [
    ...brand,
    'συντήρηση ιστοσελίδων',
    'website maintenance',
    'web support',
    'ongoing development',
    'retainer services',
    'website updates',
    'technical support',
    'website management',
    'security updates',
    'performance monitoring',
    'uptime monitoring',
    'website security',
    'web performance',
    'core web vitals',
    'speed optimization',
    'continuous development',
    'website improvements',
    'feature updates',
    'bug fixes',
    'content updates',
    'website enhancements',
    'maintenance packages',
    'support plans',
    'retainer agreements',
    'monthly maintenance',
    'website care plans',
    'ongoing support',
    'next.js maintenance',
    'react maintenance',
    'web app maintenance',
    'ecommerce maintenance',
    'cms maintenance',
    'database maintenance',
    'greek web maintenance',
    'συντήρηση ιστοσελίδων ελλάδα',
    'web support greece',
    'maintenance athens',
    'professional maintenance greece',
    'website reliability',
    'business continuity',
    'digital presence maintenance',
    'online business support',
    'website uptime',
    'professional web care',
    'web maintenance',
    'συντηρηση ιστοσελιδων',
    'website support',
    'greek web developer',
    'διαφημιστικε ιστοσελιδες',
    'κατασκευη ιστοσελιδων',
    'web development',
    'adfinity',
    'συνεχης υποστηριξη',
  ],

  // Accessibility (app/accessibility/page.tsx)
  accessibility: [
    'προσβασιμότητα',
    'accessibility',
    'WCAG',
    'ADA',
    'ατομα με αναπηρίες',
    'disabled users',
    'προσβάσιμη ιστοσελίδα',
    'accessible website',
    'adinfinity',
    'διαφημιστική εταιρεία',
    'advertising agency',
    'digital marketing',
    'ηλεκτρονικό μάρκετινγκ',
  ],

  // DSA compliance (app/dsa-compliance/page.tsx)
  'dsa-compliance': [
    'DSA compliance',
    'Digital Services Act',
    'content moderation',
    'user reporting',
    'transparency report',
    'safety measures',
    'content policy',
    'illegal content',
    'user protection',
    'Greek DSA compliance',
    'EU regulations',
    'online safety',
    'content removal',
    'reporting mechanisms',
    'DSA officer',
    'compliance procedures',
  ],

  // Report content (app/report-content/page.tsx → keywords.el)
  'report-content': [
    'αναφορά περιεχομένου',
    'αναφορά περιεχομένου dsa',
    'παράνομο περιεχόμενο',
    'ακατάλληλο περιεχόμενο',
    'ασφάλεια διαδικτύου',
    'προστασία χρηστών',
    'μηχανισμοί αναφοράς',
    'κατάργηση περιεχομένου',
    'παραβίαση περιεχομένου',
    'φόρμα αναφοράς',
    'μέτρα ασφαλείας',
    'διαδικτυακή ασφάλεια',
    'προστασία ανηλίκων',
    'επιβίωση περιεχομένου',
    'ρυθμιστική συμμόρφωση',
  ],
}

// -----------------------------------------------------------------------------
// English — only where it differs from Greek (everything else falls back to el)
// -----------------------------------------------------------------------------
const en: Record<string, string[]> = {
  // Global / site-wide (was messages/en/seo.json → keywords)
  site: [
    'adinfinity',
    'ad infinity',
    'adinity',
    'adinfit',
    'advertising agency Arta',
    'advertising agency Greece',
    'Greek advertising agency',
    'marketing agency Greece',
    'digital marketing Greece',
    'advertising services Arta',
    'social media marketing Greece',
    'graphic design Arta',
    'graphic design Greece',
    'printing services Arta',
    'flyer distribution Arta',
    'website design Greece',
    'market research Greece',
    'competitor analysis Greece',
    'branding services Greece',
    'advertising agency Cyprus',
    'Greek marketing agency',
    'Arta',
    'Greece',
    'Cyprus',
    'Epirus',
    'creative agency Greece',
    'web development Greece',
    'Greek diaspora advertising',
    'advertising agency for Greek businesses',
    'Manos Kosmas',
    'Manos Kosmas adinfinity',
    'Manos Kosmas advertising agency',
  ],

  // Report content (app/report-content/page.tsx → keywords.en)
  'report-content': [
    'report content',
    'content reporting',
    'illegal content',
    'inappropriate content',
    'DSA reporting',
    'safety reporting',
    'content moderation',
    'report abuse',
    'online safety',
    'content violation',
    'report form',
    'safety measures',
    'user protection',
    'content removal',
    'reporting mechanisms',
    'regulatory compliance',
  ],
}

export const keywords = { el, en }

/**
 * Returns the keyword list for a page in the given locale.
 * Falls back to Greek when an English list is not defined, and to the
 * site-wide list when the page key is unknown.
 */
export function getKeywords(page: string, locale: Locale = 'el'): string[] {
  return keywords[locale]?.[page] ?? el[page] ?? el.site
}
